name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

- name: Install Dependencies
        run: |
          sudo apt-get update
          # یہاں ہم سسٹم والا cython3 اور ضروری ٹولز ڈال رہے ہیں
          sudo apt-get install -y python3-pip cython3 libffi-dev 
          pip install --upgrade pip
          # پائتھن کے لیے مخصوص مستحکم ورژن
          pip install "Cython<3.0" 
          pip install buildozer

      - name: Build with Buildozer
        # اب ہم کسی ایکشن پر منحصر نہیں، براہ راست کمانڈ چلائیں گے
        run: |
          yes | buildozer android debug
