name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config python3-pip cython3 libffi-dev m4 libltdl-dev
          pip install --upgrade pip
          pip install "Cython<3.0" 
          pip install buildozer setuptools

      - name: Force Link Libtool Macros
        run: |
          # یہ حصہ اس LT_SYS_SYMBOL_USCORE والے ایرر کو جڑ سے ختم کرے گا
          sudo cp /usr/share/aclocal/libtool.m4 /usr/share/aclocal/ltoptions.m4 /usr/share/aclocal/ltsugar.m4 /usr/share/aclocal/ltversion.m4 /usr/share/aclocal/lt~obsolete.m4 .
          echo "AC_CONFIG_MACRO_DIRS([.])" >> configure.ac || true

      - name: Build with Buildozer
        run: |
          # اب ہم لائسنس خودکار قبول کر کے بلڈ شروع کریں گے
          yes | buildozer android debug
